-- changeset bertrand:9

ALTER TABLE players ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tournaments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE matches ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
